/** @format */

import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
dotenv.config();

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync(process.env.USER_PASSWORD),
      isAdmin: false,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync(process.env.USER_PASSWORD),
      isAdmin: false,
    },
    {
      name: 'Ephraim',
      email: 'ephraim@example.com',
      password: bcrypt.hashSync(process.env.ADMIN_PASSWORD),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: 'Herbal Essences Shampoo',
      slug: 'herbal-essences-shampoo',
      category: 'Shampoo',
      image: '/image/herbal-essences-shampoo.png',
      price: 12.99,
      countInStock: 50,
      brand: 'Herbal Essences',
      rating: 4.8,
      numReviews: 120,
      description: [
        'Nourishing and hydrating shampoo for all hair types.',
        'Infused with essential botanicals to cleanse and moisturize.',
        'Leaves hair feeling soft, smooth, and revitalized.',
        'Ideal for daily use and suitable for all hair textures.',
      ].join('\n'),
    },
    {
      name: 'Pantene Conditioner',
      slug: 'pantene-conditioner',
      category: 'Conditioner',
      image: '/image/pantene-conditioner.png',
      price: 14.99,
      countInStock: 40,
      brand: 'Pantene',
      rating: 4.5,
      numReviews: 80,
      description: [
        'Smooth and silky conditioner for daily use.',
        'Enhances shine and manages frizz for healthy-looking hair.',
        'Enriched with Pro-V nutrients to nourish and strengthen hair.',
        'Provides lightweight conditioning without weighing hair down.',
      ].join('\n'),
    },
    {
      name: 'Garnier Fructis Styling Gel',
      slug: 'garnier-fructis-styling-gel',
      category: 'Styling',
      image: '/image/garnier-fructis-styling-gel.png',
      price: 8.99,
      countInStock: 60,
      brand: 'Garnier Fructis',
      rating: 4.3,
      numReviews: 90,
      description: [
        'Strong hold gel for all-day styling.',
        'Formulated with fruit micro-waxes for long-lasting hold.',
        'Adds texture and definition to hair for versatile styling options.',
        'Non-greasy formula that rinses out easily.',
      ].join('\n'),
    },
    {
      name: 'Organic Root Stimulator Relaxer',
      slug: 'ors-relaxer',
      category: 'Relaxers',
      image: '/image/organic-root-stimulator-relaxer.png',
      price: 15.99,
      countInStock: 20,
      brand: 'ORS',
      rating: 4.6,
      numReviews: 50,
      description: [
        'Gentle relaxer for smooth and straight hair.',
        'Infused with natural oils to nourish and moisturize hair strands.',
        'Provides gentle conditioning while relaxing curls.',
        'Suitable for all hair types and safe for regular use.',
      ].join('\n'),
    },
    {
      name: 'SheaMoisture Curl Enhancing Smoothie',
      slug: 'shea-moisture-curl-enhancing-smoothie',
      category: 'Organic',
      image: '/image/shea-moisture-curl-enhancing-smoothie.png',
      price: 18.99,
      countInStock: 25,
      brand: 'SheaMoisture',
      rating: 4.7,
      numReviews: 110,
      description: [
        'Organic curl enhancer for natural curls and waves.',
        'Rich blend of shea butter and coconut oil for deep hydration.',
        'Defines curls and reduces frizz for manageable styling.',
        'Restores natural curl pattern without weighing hair down.',
      ].join('\n'),
    },
    {
      name: 'TRESemmé Hair Brush',
      slug: 'tresemme-hair-brush',
      category: 'Accessories',
      image: '/image/tresemme-hair-brush.png',
      price: 10.99,
      countInStock: 100,
      brand: 'TRESemmé',
      rating: 4.4,
      numReviews: 70,
      description: [
        'High-quality brush for smooth and detangled hair.',
        'Designed with nylon bristles to gently glide through hair.',
        'Ergonomic handle for comfortable styling and control.',
        'Ideal for daily use and suitable for all hair types.',
      ].join('\n'),
    },
    {
      name: "L'Oréal Paris Elvive Shampoo",
      slug: 'loreal-elvive-shampoo',
      category: 'Shampoo',
      image: '/image/loreal-elvive-shampoo.png',
      price: 9.99,
      countInStock: 45,
      brand: "L'Oréal Paris",
      rating: 4.6,
      numReviews: 150,
      description: [
        'Revitalizing shampoo for damaged hair.',
        'Infused with protein and ceramide to strengthen hair fibers.',
        'Restores vitality and enhances shine for healthier-looking hair.',
        'Gentle formula suitable for daily use and all hair textures.',
      ].join('\n'),
    },
    {
      name: 'OGX Coconut Miracle Oil Conditioner',
      slug: 'ogx-coconut-conditioner',
      category: 'Conditioner',
      image: '/image/ogx-coconut-conditioner.png',
      price: 11.99,
      countInStock: 35,
      brand: 'OGX',
      rating: 4.8,
      numReviews: 95,
      description: [
        'Ultra-moisturizing conditioner with coconut oil.',
        'Nourishes and hydrates hair for softness and shine.',
        'Restores elasticity and strength to dry, damaged hair.',
        "Lightweight formula that won't weigh hair down.",
      ].join('\n'),
    },
    {
      name: 'Aussie 3 Minute Miracle Treatment',
      slug: 'aussie-3-minute-treatment',
      category: 'Treatments',
      image: '/image/aussie-3-minute-treatment.png',
      price: 5.99,
      countInStock: 20,
      brand: 'Aussie',
      rating: 4.7,
      numReviews: 180,
      description: [
        'Deep conditioning treatment for smooth and shiny hair.',
        'Intensive formula with Australian balm mint extract.',
        'Revitalizes dull hair and restores moisture balance.',
        'Leaves hair silky and manageable after just 3 minutes.',
      ].join('\n'),
    },
    {
      name: 'Dove Style+Care Hairspray',
      slug: 'dove-hairspray',
      category: 'Styling',
      image: '/image/dove-hairspray.png',
      price: 6.99,
      countInStock: 50,
      brand: 'Dove',
      rating: 4.2,
      numReviews: 130,
      description: [
        'Strong hold hairspray with a natural finish.',
        'Provides long-lasting control and humidity resistance.',
        'Non-sticky formula that brushes out easily.',
        'Adds shine and leaves hair feeling soft and touchable.',
      ].join('\n'),
    },
    {
      name: 'Mizani Butter Blend Relaxer',
      slug: 'mizani-butter-blend-relaxer',
      category: 'Relaxers',
      image: '/image/mizani-butter-blend-relaxer.png',
      price: 19.99,
      countInStock: 15,
      brand: 'Mizani',
      rating: 4.5,
      numReviews: 40,
      description: [
        'Professional-grade relaxer for smooth and manageable hair.',
        'Enriched with shea butter and cocoa butter for nourishment.',
        'Minimizes scalp irritation and conditions hair during relaxing.',
        'Leaves hair sleek, soft, and easy to style.',
      ].join('\n'),
    },
    {
      name: 'Avalon Organics Thickening Shampoo',
      slug: 'avalon-organics-thickening-shampoo',
      category: 'Organic',
      image: '/image/avalon-organics-thickening-shampoo.png',
      price: 14.99,
      countInStock: 25,
      brand: 'Avalon Organics',
      rating: 4.3,
      numReviews: 75,
      description: [
        'Biotin B-Complex thickening shampoo for fuller hair.',
        'Strengthens hair strands and adds volume for thicker-looking hair.',
        'Gentle formula with organic botanicals to nourish the scalp.',
        'Free from parabens, sulfates, and synthetic fragrances.',
      ].join('\n'),
    },
    {
      name: 'Wet Brush Original Detangler',
      slug: 'wet-brush-detangler',
      category: 'Accessories',
      image: '/image/wet-brush-detangler.png',
      price: 7.99,
      countInStock: 80,
      brand: 'Wet Brush',
      rating: 4.6,
      numReviews: 100,
      description: [
        'Gentle detangling brush for wet or dry hair.',
        'Exclusive IntelliFlex bristles glide through knots with ease.',
        'Minimizes breakage and split ends for healthier hair.',
        'Ergonomic handle for comfortable use on all hair types.',
      ].join('\n'),
    },

    {
      name: 'Biolage Colorlast Shampoo',
      slug: 'biolage-colorlast-shampoo',
      category: 'Shampoo',
      image: '/image/biolage-colorlast-shampoo.png',
      price: 21.99,
      countInStock: 30,
      brand: 'Biolage',
      rating: 4.8,
      numReviews: 110,
      description: [
        'Shampoo for color-treated hair to preserve vibrancy.',
        'Maintains salon-vibrant color for up to 9 weeks.',
        'Infused with orchid extract for gentle cleansing.',
        'Paraben-free formula suitable for all hair types.',
      ].join('\n'),
    },
    {
      name: 'Living Proof Restore Conditioner',
      slug: 'living-proof-restore-conditioner',
      category: 'Conditioner',
      image: '/image/living-proof-restore-conditioner.png',
      price: 29.99,
      countInStock: 20,
      brand: 'Living Proof',
      rating: 4.6,
      numReviews: 100,
      description: [
        'Conditioner for damaged hair to restore moisture and strength.',
        'Patented Healthy Hair Molecule (OFPMA) for smoothness.',
        'Improves hair health and combability with regular use.',
        'Sulfate-free and safe for chemically treated hair.',
      ].join('\n'),
    },
    {
      name: 'Olaplex Hair Perfector No. 3',
      slug: 'olaplex-hair-perfector',
      category: 'Treatments',
      image: '/image/olaplex-hair-perfector.png',
      price: 28.0,
      countInStock: 25,
      brand: 'Olaplex',
      rating: 4.9,
      numReviews: 300,
      description: [
        'Repairing treatment to strengthen and protect hair structure.',
        'Reduces breakage and visibly strengthens hair.',
        'Suitable for all hair types, including colored and chemically treated hair.',
        'Apply weekly to improve hair texture and manageability.',
      ].join('\n'),
    },
    {
      name: 'TIGI Bed Head Wax Stick',
      slug: 'tigi-wax-stick',
      category: 'Styling',
      image: '/image/tigi-wax-stick.png',
      price: 11.99,
      countInStock: 40,
      brand: 'TIGI',
      rating: 4.4,
      numReviews: 85,
      description: [
        'Styling wax for flexible hold and texture.',
        'Creates defined, piecey styles without stiffness.',
        'Adds shine and controls frizz for a polished look.',
        'Ideal for short to medium-length hair.',
      ].join('\n'),
    },
    {
      name: 'SoftSheen-Carson Optimum Care Relaxer',
      slug: 'softsheen-carson-relaxer',
      category: 'Relaxers',
      image: '/image/softsheen-carson-relaxer.png',
      price: 13.99,
      countInStock: 20,
      brand: 'SoftSheen-Carson',
      rating: 4.5,
      numReviews: 60,
      description: [
        'Relaxer kit for soft and smooth hair.',
        'Formulated with coconut oil and ceramide technology.',
        'Gentle on the scalp with minimal irritation.',
        'Results in straighter hair with natural movement.',
      ].join('\n'),
    },
    {
      name: 'Andalou Naturals Argan Oil & Shea Shampoo',
      slug: 'andalou-naturals-argan-oil-shampoo',
      category: 'Organic',
      image: '/image/andalou-naturals-argan-oil-shampoo.png',
      price: 12.99,
      countInStock: 30,
      brand: 'Andalou Naturals',
      rating: 4.6,
      numReviews: 65,
      description: [
        'Moisturizing shampoo with argan oil and shea butter.',
        'Nourishes and hydrates hair for improved manageability.',
        'Enhances shine and reduces frizz for softer hair.',
        '100% vegetarian ingredients with no sulfates or parabens.',
      ].join('\n'),
    },
    {
      name: 'Conair 1875 Watt Hair Dryer',
      slug: 'conair-hair-dryer',
      category: 'Accessories',
      image: '/image/conair-hair-dryer.png',
      price: 24.99,
      countInStock: 50,
      brand: 'Conair',
      rating: 4.4,
      numReviews: 140,
      description: [
        'Powerful hair dryer for fast drying and styling.',
        'Features tourmaline ceramic technology for smooth results.',
        'Includes multiple heat and speed settings for versatility.',
        'Lightweight design with a comfortable grip for ease of use.',
      ].join('\n'),
    },
    // Add more products as needed...

    {
      name: 'Kerastase Nutritive Shampoo',
      slug: 'kerastase-nutritive-shampoo',
      category: 'Shampoo',
      image: '/image/kerastase-nutritive-shampoo.png',
      price: 32.99,
      countInStock: 25,
      brand: 'Kerastase',
      rating: 4.7,
      numReviews: 115,
      description: [
        'Nourishing shampoo for dry and sensitive hair.',
        'Infused with irisome complex for long-lasting nutrition.',
        'Leaves hair feeling softer, smoother, and more manageable.',
        'Protects against dryness and enhances hair fiber vitality.',
      ].join('\n'),
    },
    {
      name: 'Redken All Soft Conditioner',
      slug: 'redken-all-soft-conditioner',
      category: 'Conditioner',
      image: '/image/redken-all-soft-conditioner.png',
      price: 25.99,
      countInStock: 30,
      brand: 'Redken',
      rating: 4.8,
      numReviews: 150,
      description: [
        'Conditioner for soft, manageable hair.',
        'Enriched with argan oil to nourish and hydrate dry hair.',
        'Improves hair texture and adds shine for a polished look.',
        'Provides intense softness, replenishment, and strength.',
      ].join('\n'),
    },
    {
      name: 'Wella FusionPlex Intense Repair Mask',
      slug: 'wella-fusionplex-repair-mask',
      category: 'Treatments',
      image: '/image/wella-fusionplex-repair-mask.png',
      price: 40.0,
      countInStock: 15,
      brand: 'Wella',
      rating: 4.9,
      numReviews: 200,
      description: [
        'Repair mask for damaged hair with silksteel fusion technology.',
        'Deeply penetrates the hair shaft to repair and protect.',
        'Restores hair health, resilience, and strength.',
        'Ideal for stressed and damaged hair in need of intensive care.',
      ].join('\n'),
    },
    {
      name: 'Aveda Control Force Hairspray',
      slug: 'aveda-control-force-hairspray',
      category: 'Styling',
      image: '/image/aveda-control-force-hairspray.png',
      price: 29.99,
      countInStock: 35,
      brand: 'Aveda',
      rating: 4.6,
      numReviews: 90,
      description: [
        'Firm hold hairspray with natural, long-lasting hold.',
        'Provides humidity defense for up to 24 hours.',
        'Offers all-day control without stiffness or flaking.',
        'Infused with organic essential oils for a refreshing aroma.',
      ].join('\n'),
    },
    {
      name: 'Vitale Olive Oil Relaxer',
      slug: 'vitale-olive-oil-relaxer',
      category: 'Relaxers',
      image: '/image/vitale-olive-oil-relaxer.png',
      price: 16.99,
      countInStock: 20,
      brand: 'Vitale',
      rating: 4.5,
      numReviews: 55,
      description: [
        'Olive oil infused relaxer for smooth and shiny hair.',
        'Formulated to protect hair during the relaxing process.',
        'Conditions and moisturizes hair for improved manageability.',
        'Provides a straighter, sleeker look without scalp irritation.',
      ].join('\n'),
    },
    {
      name: 'John Masters Organics Shampoo',
      slug: 'john-masters-organics-shampoo',
      category: 'Organic',
      image: '/image/john-masters-organics-shampoo.png',
      price: 22.99,
      countInStock: 25,
      brand: 'John Masters Organics',
      rating: 4.7,
      numReviews: 100,
      description: [
        'Organic shampoo with lavender and rosemary for normal hair.',
        'Gently cleanses without stripping natural oils.',
        'Promotes healthy scalp and balanced moisture levels.',
        'Leaves hair feeling clean, soft, and refreshed.',
      ].join('\n'),
    },
    {
      name: 'Revlon One-Step Hair Dryer and Volumizer',
      slug: 'revlon-hair-dryer-volumizer',
      category: 'Accessories',
      image: '/image/revlon-hair-dryer-volumizer.png',
      price: 59.99,
      countInStock: 40,
      brand: 'Revlon',
      rating: 4.8,
      numReviews: 300,
      description: [
        '2-in-1 hair dryer and volumizer for salon-quality blowouts.',
        'Ionic technology for faster drying and less heat damage.',
        'Creates voluminous styles with enhanced shine and smoothness.',
        'Lightweight and ergonomic design for comfortable styling.',
      ].join('\n'),
    },
    {
      name: 'Suave Professionals Shampoo',
      slug: 'suave-professionals-shampoo',
      category: 'Shampoo',
      image: '/image/suave-professionals-shampoo.png',
      price: 8.99,
      countInStock: 50,
      brand: 'Suave',
      rating: 4.3,
      numReviews: 80,
      description: [
        'Affordable shampoo for smooth and manageable hair.',
        'Infused with keratin amino acids to strengthen hair fibers.',
        'Leaves hair shiny, healthy-looking, and easy to style.',
        'Suitable for daily use and all hair types.',
      ].join('\n'),
    },
    {
      name: 'Head & Shoulders Conditioner',
      slug: 'head-and-shoulders-conditioner',
      category: 'Conditioner',
      image: '/image/head-and-shoulders-conditioner.png',
      price: 12.99,
      countInStock: 45,
      brand: 'Head & Shoulders',
      rating: 4.5,
      numReviews: 95,
      description: [
        'Anti-dandruff conditioner for healthy scalp and hair.',
        'Infused with pyrithione zinc to control flaking and itching.',
        'Provides moisture and nourishment for soft, shiny hair.',
        'Clinically proven to leave hair flake-free* (*visible flakes with regular use).',
      ].join('\n'),
    },
    {
      name: "L'Oréal Paris Total Repair 5 Damage Erasing Balm",
      slug: 'loreal-total-repair-balm',
      category: 'Treatments',
      image: '/image/loreal-total-repair-balm.png',
      price: 10.99,
      countInStock: 30,
      brand: "L'Oréal Paris",
      rating: 4.6,
      numReviews: 130,
      description: [
        'Damage repair treatment for stronger and healthier hair.',
        'Targets five signs of hair damage: split ends, weakness, roughness, dullness, and dehydration.',
        'Instantly repairs and nourishes hair fibers.',
        'Leaves hair smoother, shinier, and more manageable.',
      ].join('\n'),
    },
    // Add more products as needed...
  ],
};

export default data;
